name: "Pull Request Labeler"
on:
  push:
    branches:
      - feat/support_for_importing_unarmored_key
  pull_request_target:
    branches:
      - main
#  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#      - name: Label PR
#        uses: actions/labeler@v5
#        with:
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
