name: Proto check
on: [pull_request]
jobs:
  proto-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker-practice/actions-setup-docker@master
      - run: pwd
      # - name: lint
      #   run: docker run -v pwd:/workspace --workdir /workspace bufbuild/buf check lint --error-format=json
      # - name: check-breakage
      #   run: docker run -v pwd:/workspace --workdir /workspace bufbuild/buf --against-input .git#branch=master
